spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: debug
